In [10]:
import pandas as pd
import geopandas as gpd
import pprint as pp

In [3]:
pd.set_option("display.max_columns", None)

## Load data

In [4]:
lunch = pd.read_csv("../raw_data/ELSI.csv", header=3)

In [7]:
lunch = lunch.infer_objects()

In [14]:
lunch.dtypes

County Name                                                          object
County Number [Public School] 2018-19                               float64
Total Number of Public Schools [Public School] 2018-19              float64
Total Number of Public Schools [Public School] 2017-18              float64
Total Number of Public Schools [Public School] 2016-17              float64
Total Number of Public Schools [Public School] 2015-16              float64
Total Number of Public Schools [Public School] 2014-15              float64
Free Lunch Eligible [Public School] 2018-19                         float64
Free Lunch Eligible [Public School] 2017-18                         float64
Free Lunch Eligible [Public School] 2016-17                         float64
Free Lunch Eligible [Public School] 2015-16                         float64
Free Lunch Eligible [Public School] 2014-15                          object
Reduced-price Lunch Eligible Students [Public School] 2018-19        object
Reduced-price Lunch Eligible Students [Public School] 2017-18        object
Reduced-price Lunch Eligible Students [Public School] 2016-17        object
Reduced-price Lunch Eligible Students [Public School] 2015-16        object
Reduced-price Lunch Eligible Students [Public School] 2014-15        object
American Indian/Alaska Native Students [Public School] 2018-19       object
American Indian/Alaska Native Students [Public School] 2017-18       object
American Indian/Alaska Native Students [Public School] 2016-17       object
American Indian/Alaska Native Students [Public School] 2015-16       object
American Indian/Alaska Native Students [Public School] 2014-15       object
Asian or Asian/Pacific Islander Students [Public School] 2018-19     object
Asian or Asian/Pacific Islander Students [Public School] 2017-18     object
Asian or Asian/Pacific Islander Students [Public School] 2016-17     object
Asian or Asian/Pacific Islander Students [Public School] 2015-16     object
Asian or Asian/Pacific Islander Students [Public School] 2014-15     object
Hispanic Students [Public School] 2018-19                           float64
Hispanic Students [Public School] 2017-18                            object
Hispanic Students [Public School] 2016-17                           float64
Hispanic Students [Public School] 2015-16                           float64
Hispanic Students [Public School] 2014-15                            object
Black Students [Public School] 2018-19                              float64
Black Students [Public School] 2017-18                               object
Black Students [Public School] 2016-17                              float64
Black Students [Public School] 2015-16                              float64
Black Students [Public School] 2014-15                               object
White Students [Public School] 2018-19                              float64
White Students [Public School] 2017-18                               object
White Students [Public School] 2016-17                              float64
White Students [Public School] 2015-16                              float64
White Students [Public School] 2014-15                               object
Hawaiian Nat./Pacific Isl. Students [Public School] 2018-19          object
Hawaiian Nat./Pacific Isl. Students [Public School] 2017-18          object
Hawaiian Nat./Pacific Isl. Students [Public School] 2016-17          object
Hawaiian Nat./Pacific Isl. Students [Public School] 2015-16          object
Hawaiian Nat./Pacific Isl. Students [Public School] 2014-15          object
Two or More Races Students [Public School] 2018-19                  float64
Two or More Races Students [Public School] 2017-18                   object
Two or More Races Students [Public School] 2016-17                  float64
Two or More Races Students [Public School] 2015-16                  float64
Two or More Races Students [Public School] 2014-15                   object
Total Race/Ethnicity [Public School] 2018-19                        float64
Total Race/Ethnicity [Public School] 2017-18                        float64
Total Race/Ethnicity [Public School] 2016-17                         object
Total Race/Ethnicity [Public School] 2015-16                        float64
Total Race/Ethnicity [Public School] 2014-15                        float64
dtype: object

In [20]:
lunch.iloc[:, 1:-1]

,County Number [Public School] 2018-19,Total Number of Public Schools [Public School] 2018-19,Total Number of Public Schools [Public School] 2017-18,Total Number of Public Schools [Public School] 2016-17,Total Number of Public Schools [Public School] 2015-16,Total Number of Public Schools [Public School] 2014-15,Free Lunch Eligible [Public School] 2018-19,Free Lunch Eligible [Public School] 2017-18,Free Lunch Eligible [Public School] 2016-17,Free Lunch Eligible [Public School] 2015-16,Free Lunch Eligible [Public School] 2014-15,Reduced-price Lunch Eligible Students [Public School] 2018-19,Reduced-price Lunch Eligible Students [Public School] 2017-18,Reduced-price Lunch Eligible Students [Public School] 2016-17,Reduced-price Lunch Eligible Students [Public School] 2015-16,Reduced-price Lunch Eligible Students [Public School] 2014-15,American Indian/Alaska Native Students [Public School] 2018-19,American Indian/Alaska Native Students [Public School] 2017-18,American Indian/Alaska Native Students [Public School] 2016-17,American Indian/Alaska Native Students [Public School] 2015-16,American Indian/Alaska Native Students [Public School] 2014-15,Asian or Asian/Pacific Islander Students [Public School] 2018-19,Asian or Asian/Pacific Islander Students [Public School] 2017-18,Asian or Asian/Pacific Islander Students [Public School] 2016-17,Asian or Asian/Pacific Islander Students [Public School] 2015-16,Asian or Asian/Pacific Islander Students [Public School] 2014-15,Hispanic Students [Public School] 2018-19,Hispanic Students [Public School] 2017-18,Hispanic Students [Public School] 2016-17,Hispanic Students [Public School] 2015-16,Hispanic Students [Public School] 2014-15,Black Students [Public School] 2018-19,Black Students [Public School] 2017-18,Black Students [Public School] 2016-17,Black Students [Public School] 2015-16,Black Students [Public School] 2014-15,White Students [Public School] 2018-19,White Students [Public School] 2017-18,White Students [Public School] 2016-17,White Students [Public School] 2015-16,White Students [Public School] 2014-15,Hawaiian Nat./Pacific Isl. Students [Public School] 2018-19,Hawaiian Nat./Pacific Isl. Students [Public School] 2017-18,Hawaiian Nat./Pacific Isl. Students [Public School] 2016-17,Hawaiian Nat./Pacific Isl. Students [Public School] 2015-16,Hawaiian Nat./Pacific Isl. Students [Public School] 2014-15,Two or More Races Students [Public School] 2018-19,Two or More Races Students [Public School] 2017-18,Two or More Races Students [Public School] 2016-17,Two or More Races Students [Public School] 2015-16,Two or More Races Students [Public School] 2014-15,Total Race/Ethnicity [Public School] 2018-19,Total Race/Ethnicity [Public School] 2017-18,Total Race/Ethnicity [Public School] 2016-17,Total Race/Ethnicity [Public School] 2015-16
0,37001.0,39.0,39.0,39.0,39.0,39.0,12929.0,12853.0,12954.0,13169.0,12358,1073,1053,1364,1221,1530,85,85,95,107,113,377,368,357,335,341,6378.0,6232,6037.0,5869.0,5651,5439.0,5356,5278.0,5260.0,5077,11372.0,11594,11896.0,12127.0,12388,23,28,27,28,31,1196.0,1129,1079.0,1041.0,951,24870.0,24792.0,†,24767.0
1,37003.0,11.0,11.0,11.0,10.0,10.0,1932.0,1997.0,2201.0,2345.0,2207,254,297,398,413,458,5,4,4,4,8,75,76,81,95,102,496.0,498,480.0,471.0,456,188.0,196,200.0,209.0,211,3885.0,3957,3994.0,4104.0,4278,3,4,4,3,4,213.0,218,212.0,198.0,198,4865.0,4953.0,†,5084.0
2,37005.0,4.0,4.0,4.0,4.0,4.0,736.0,784.0,807.0,1217.0,1219,128,124,120,28,45,4,5,6,6,6,3,5,5,4,3,338.0,336,316.0,328.0,303,8.0,10,9.0,11.0,9,1031.0,1018,1055.0,1116.0,1132,"=""0""","=""0""","=""0""","=""0""","=""0""",32.0,32,29.0,27.0,24,1416.0,1406.0,†,1492.0
3,37007.0,11.0,10.0,11.0,11.0,11.0,3144.0,3294.0,3265.0,3400.0,2449,"=""0""","=""0""","=""0""","=""0""",246,9,8,11,14,12,54,62,52,57,58,179.0,173,143.0,136.0,136,1798.0,1891,1905.0,1975.0,2005,1015.0,1105,1136.0,1161.0,1227,1,2,"=""0""","=""0""","=""0""",119.0,110,99.0,91.0,88,3175.0,3351.0,†,3434.0
4,37009.0,6.0,6.0,5.0,5.0,5.0,1430.0,1416.0,1491.0,1577.0,1627,301,335,301,352,350,3,3,1,2,2,18,17,16,17,16,376.0,347,328.0,315.0,301,11.0,18,16.0,18.0,15,2588.0,2614,2698.0,2791.0,2871,"=""0""","=""0""","=""0""","=""0""","=""0""",53.0,48,36.0,32.0,35,3049.0,3047.0,†,3175.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,37199.0,9.0,9.0,9.0,9.0,9.0,906.0,912.0,1009.0,1007.0,1007,162,221,212,231,226,9,8,7,7,5,1,"=""0""",1,2,1,298.0,304,302.0,281.0,276,12.0,11,12.0,15.0,15,1789.0,1853,1857.0,1875.0,1915,1,1,"=""0""","=""0""","=""0""",38.0,38,36.0,26.0,23,2148.0,2215.0,†,2206.0
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN